services:
  postgres:
    image: postgres
    volumes:
      - ./initial-load.sql:/docker-entrypoint-initdb.d/initial-load.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"